shared: &shared
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["USER"] || "postgres" %>

development:
  <<: *shared
  database: dumper_development

test:
  <<: *shared
  database: dumper_test
  min_messages: WARNING
